export const metadata = {
  title: 'My App',
  description: 'Generated by Launchstack',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
